config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :suspects, only: %i[index show new create destroy] # do
   # resources :guesses, only: %i[new create]
  # end
  resources :guesses, only: %i[destroy new create show index]
  resources :weapons, only: %i[index show]
  resources :locations, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :suspect
  belongs_to :weapon
  belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :guesses, dependent: :destroy
  has_many :weapons, through: :guesses
  has_many :suspects, through: :guesses
  validates :room, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/suspect.rb
class Suspect < ApplicationRecord
  has_many :guesses, dependent: :destroy
  has_many :weapons, through: :guesses
  has_many :locations, through: :guesses
  validates :name, presence: true, uniqueness: true
  validates :color, presence: true, inclusion: { in: %w[red yellow purple white black green blue] }
  has_one_attached :photo

  def to_label
    name.split.map(&:capitalize).join(' ')
  end
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  has_many :guesses, dependent: :destroy
  has_many :weapons, through: :guesses
  has_many :suspects, through: :guesses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/suspects_controller.rb
class SuspectsController < ApplicationController
  def index
    @suspects = Suspect.all
  end

  def show
    @suspect = Suspect.find(params[:id])
  end

  def new
    @suspect = Suspect.new
  end

  def create
    @suspect = Suspect.new(suspect_params)
    if @suspect.save
      redirect_to suspect_path(@suspect)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @suspect = Suspect.find(params[:id])
    @suspect.destroy
    if @suspect.destroy
      redirect_to suspect_path(@suspect)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def suspect_params
    params.require(:suspect).permit(:name, :color, :photo)
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    @weapons = Weapon.all
  end

  def show
    @weapon = Weapon.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/suspects_helper.rb
module SuspectsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCluedo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<div class="container">
  <h1>Visit the Rooms!</h1>
  <div class="cards text-decoration-none">
    <% @locations.each do |location| %>
      <%= link_to location_path(location) do%>
        <div class="card text-decoration-none">
          <img src="https://via.placeholder.com/150">
          <div class="card-details text-decoration-none">
            <h3><%= location.room %></h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to suspects_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-magnifying-glass fa-xl"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Suspects", suspects_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Suspect", new_suspect_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Weapons", weapons_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Rooms", locations_path, class: "nav-link" %>
        </li>
        <%# else %>
        <!--li class="nav-item"-->
        <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
        <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/suspects/_form.html.erb
<%= simple_form_for @suspect do |f| %>
  <%= f.input :name, placeholder: 'Enter Name' %>
  <%= f.input :color, placeholder: 'Enter Color' %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: 'btn btn-secondary' %>
<% end %>

app/views/suspects/index.html.erb
<div class="container text-decoration-none">
  <h1>Meet the Suspects!</h1>
  <h2>The Usual Suspects</h2>
  <div class="cards text-decoration-none">
    <% @suspects[0..5].each do |suspect| %>
      <%= link_to suspect_path(suspect) do%>
        <div class="card <%= suspect.color %> text-decoration-none">
          <img src="https://via.placeholder.com/150">
          <div class="card-details text-decoration-none">
            <h3><%= suspect.to_label %></h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <h2>Additional Suspects</h2>
  <div class="cards text-decoration-none">
    <% @suspects[6..].each do |suspect| %>
      <%= link_to suspect_path(suspect) do%>
        <div class="card <%= suspect.color %> text-decoration-none">
          <img src="https://via.placeholder.com/150">
          <div class="card-details text-decoration-none">
            <h3><%= suspect.to_label %></h3>
            <%= link_to suspect_path(suspect), data: { turbo_method: :delete, turbo_confirm: "Bump Off #{suspect.to_label}?" } do %>
              <i class="fa-solid fa-gun"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/suspects/new.html.erb
<div class="container">
  <h1>Add a new Suspect</h1>
  <div class="form">
    <%= render 'form' %>
  </div>
</div>

app/views/suspects/show.html.erb
<div class="container <%= @suspect.color %>">
  <h1><%= @suspect.to_label %></h1>
</div>

app/views/weapons/index.html.erb
<div class="container">
  <h1>View the Weapons!</h1>
  <div class="cards text-decoration-none">
    <% @weapons.each do |weapon| %>
      <%= link_to weapon_path(weapon) do%>
        <div class="card text-decoration-none">
          <img src="https://via.placeholder.com/150">
          <div class="card-details text-decoration-none">
            <h3><%= weapon.name %></h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>